version: "3.6"
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
      target: client
    image: starlightcruises-frontend
    restart: always
    ports:
      - "1500:1500"
    networks:
      - dbnetwork
    volumes:
      - ./frontend:/var/www/node
  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: server
    image: starlightcruises-backend
    restart: always
    ports: 
      - "3000:3000"
    networks: 
      - dbnetwork 
    #volumes:
      # - type: bind
        # source: ./nodewebservice
        # target: /var/www/node    
      # - ./Server:/var/www/dotnet
  mongodb:
    image: mongo:latest
    volumes:
      - ./.mdb-data:/data/db
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "starlightcruises"
      #generatemeapassword
      MONGO_INITDB_ROOT_PASSWORD: ""
    networks: 
      - dbnetwork   
  mongo-express:
    image: mongo-express:latest
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_SERVER: "mongodb"
      ME_CONFIG_MONGODB_ADMINUSERNAME: "insitesolutions"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "LoAp10*721"
      ME_CONFIG_MONGODB_PORT: 27017
    depends_on:
      - mongodb
    networks: 
      - dbnetwork       
networks:
    dbnetwork: